apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-backend-kube
  labels:
    app: product-backend-kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-backend-kube
  template:
    metadata:
      labels:
        app: product-backend-kube
    spec:
      containers:
      - name: product-backend-kube
        image: amnashahid/aspnet-be-img-22