version: '3.4'

volumes:
  datafiles:


services:
  mysqldb:
    image: mysql:8.0.22
    ports:
      - "1336:3306"
    volumes:
      - datafiles:/var/lib/mysql
      - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    environment:
      MYSQL_DATABASE: productcatalog
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: sa
  #Api  Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    ports:
      - "5000:80"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontendapp:
    image: amnashahid/devops-be
    container_name: frontend-dev-2
    ports:
      - 3000:3000
